export const BOOKMARKS_INITIALIZING = 'BOOKMARKS_INITIALIZING';
export const BOOKMARKS_INITIALIZED = 'BOOKMARKS_INITIALIZED';
export const BOOKMARK_ADD_TO_FAVORITES = 'BOOKMARK_ADD_TO_FAVORITES';
export const BOOKMARK_REMOVE_FROM_FAVORITES = 'BOOKMARK_REMOVE_FROM_FAVORITES';
export const BOOKMARK_UPDATED = 'BOOKMARK_UPDATED';
export const BOOKMARK_DELETE = 'BOOKMARK_DELETE';

export const BOOKMARKS_FAVORITES_INITIALIZING = 'BOOKMARKS_FAVORITES_INITIALIZING';
export const BOOKMARKS_FAVORITES_INITIALIZED = 'BOOKMARKS_FAVORITES_INITIALIZED';