export const LABELS_INITIALIZING = "LABELS_INITIALIZING";
export const LABELS_INITIALIZED = "LABELS_INITIALIZED";

export const LABELS_DETAILS_INITIALIZING = "LABELS_DETAILS_INITIALIZING";
export const LABELS_DETAILS_INITIALIZED = "LABELS_DETAILS_INITIALIZED";
