name: Release CI

on:
  push:
    branches: [ release ]
  workflow_dispatch:

env:
  BUILD_ENV: prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --prefix web
      - run: npm run config --prefix web -- --env $BUILD_ENV
      - run: npm run build --prefix web -- --configuration production

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: '*'
          cdk_args: ${{ format('--require-approval never -c env={0} -c dbTableArn={1} -c dbTableStreamArn={2} -c userPoolClientId={3} -c userPoolArn={4} -c userPoolId={5}', env.BUILD_ENV, secrets.AWS_DB_TABLE_ARN, secrets.AWS_DB_TABLE_STREAM, secrets.AWS_USER_POOL_CLIENT_ID, secrets.AWS_USER_POOL_ARN, secrets.AWS_USER_POOL_ID) }}
          working_dir: 'backend'
          debug_log: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: 'us-east-1'
